#    geoCore - a QGIS plugin for drawing drilling profiles
#    Copyright (C) 2019, 2020  Gerrit Bette, T-Systems on site services GmbH
#
#    This file is part of geoCore.
#
#    geoCore is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    geoCore is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with geoCore.  If not, see <https://www.gnu.org/licenses/>.

boxes:
    S: #shortname
        longname: sand
        width: 3.5
    T: #shortname
        longname: clay
        width: 1.0
    U: #shortname
        longname: silt
        width: 2.25
    G: #shortname
        longname: gravel
        width: 4.75
    H: #shortname
        longname: peat
        width: 5.5

descriptions:
    u4: #shortname
        longname: strong silty
    h: #shortname
        longname: humic
    fs: #shortname
        longname: fine sand
    u1: #shortname
        longname: slightly silty
    u2: #shortname
        longname: increasingly silty
    t1: #shortname
        longname: slightly clayey
    lam: #shortname
        longname: laminated
        texture: symbols/lam.svg
    as: #shortname
        longname: articulated shell
    wood: #shortname
        longname: wood
        texture: symbols/wood.svg

facies:
    st: subtidial
    it: interdidial

colors:
    gr: #shortname
        longname: gray
        code: "#c9c8c8"
    br: #shortname
        longname: brown
        code: "#b6afa1"
    ge: #shortname
        longname: yellow
        code: "#f6e8a1"
    gru: #shortname
        longname: green
        code: "#5f9288"
